### PR TITLE
Added Georgian (GE) translation

### PR DESCRIPTION
**Pull request by UltraStudioLTD**
Okey @Ryosuke839 .
I changed location of translation.
Can you merge now?

### CODE REVIEW

**Comment by UltraStudioLTD** [comment]
And also. Are there any credits for contributors? Like for translation?

**Comment by Ryosuke839** [comment]
Currently there are no credits except for that can be seen in commit history.

I think it's worth to be added in the app 🙂  #87

**Comment by Ryosuke839** [comment]
IETF language code is wrong and there are redundant untranslated resources.
I'm going to merge this into a local branch and fix them before merging into develop.

**Comment by UltraStudioLTD** [comment]
How to change interface language?

**Pull request merged**
